- name: Create the application user
  user:
    name: "{{ gunicorn_user }}"
    state: present

- name: Create the application group
  group:
    name: "{{ gunicorn_group }}"
    state: present
    system: yes

- name: Add application user to application group
  user:
    name: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    state: present
