language: python
python:
- '3.4'
addons:
  postgresql: '9.3'
install:
    - pip install -r requirements.txt
before_script:
    - psql -c 'CREATE DATABASE snussum;' -U postgres
script:
    - pep8
    - python snussum/manage.py makemigrations users relationships
    - python snussum/manage.py migrate
